name: Example - Build and push hello-run

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: GCP project ID
        required: true
      repo_id:
        description: Artifact Registry repo ID
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push
        working-directory: examples/hello-run
        run: |
          IMAGE="europe-west1-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.repo_id }}/hello-run:${GITHUB_SHA}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT


